volumes:
  storage-share:
    driver_opts:
      type: cifs
      o: user=${SMB_USER},password=${SMB_PASSWORD},file_mode=0755,dir_mode=0755,rw,uid=1000,gid=1000
      device: //${SMB_SERVER_IP}/storage-share
services:  
  #Tautulli - for plex statistics. Very useful when troubleshooting performance issues
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped