volumes:
  storage-share:
    driver_opts:
      type: cifs
      o: user=${SMB_USER},password=${SMB_PASSWORD},file_mode=0755,dir_mode=0755,rw,uid=1000,gid=1000
      device: //${SMB_SERVER_IP}/storage-share
services:
  #Overseer - allows users to request media on their own
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/seerr/config:/app/config
      - storage-share:/share #Access to the entire share
    ports:
      - 5055:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    networks:
      - default
      - notifications
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY} # Optional, only if you want to set a custom encryption key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${BASE_PATH}/homarr/icons:/app/public/icons
      - ${BASE_PATH}/homarr/data:/appdata

    ports:
      - '7575:7575'

  #Wizarr - Allows you to create a share link that you can send to users to invite them to your media server
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    environment:
      - TZ=${TZ}
    ports:
      - 5690:5690
    volumes:
      - ${BASE_PATH}/wizarr/data/database:/data/database
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_PATH}/dozzle/data:/data
    environment:
      - DOZZLE_REMOTE_AGENT=${DOZZLE_REMOTE_AGENT}:7007
    ports:
      - 8888:8080 # Changed to 8888 to avoid conflict with Sabnzbd on 8080
    networks:
      - default
      - notifications
    restart: unless-stopped

networks:
  notifications:
    external: true
    name: notifications
