volumes:
  storage-share:
    driver_opts:
      type: cifs
      o: user=${SMB_USER},password=${SMB_PASSWORD},file_mode=0755,dir_mode=0755,rw,uid=1000,gid=1000
      device: //${SMB_SERVER_IP}/storage-share
services:
  #kometa - used to create collections in plex. Example: "Most Popular Movies This Week", "Best of horror", etc.
  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TZ}
      - KOMETA_CONFIG=/config/config.yml #optional
      # - KOMETA_TIME=03:00 #optional
      # - KOMETA_RUN=True #optional
      - KOMETA_TEST=False #optional
      - KOMETA_NO_MISSING=False #optional
      - KOMETA_TIMES=01:30|02:30|03:30|04:30|05:30|06:30|07:30|08:30|09:30|10:30|11:30|12:30|13:30|14:30|15:30|16:30|17:30|18:30|19:30|20:30|21:30|22:30|23:30|00:30 #optional
    volumes:
      - ${BASE_PATH}/config:/config
      - /home/port/stacks/posterizarr/assets:/assets
    networks:
      - default
      - notifications
    restart: unless-stopped
networks:
  notifications:
    external: true
    name: notifications
